# Generated by Django 4.0.3 on 2022-05-16 23:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_person_gender'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cemetery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(blank=True, max_length=100, null=True)),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('longitude', models.CharField(blank=True, max_length=100, null=True)),
                ('latitude', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='burialplace',
            name='is_busy',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='burialplace',
            name='is_reserved',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='person',
            name='iin',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='burialplace',
            name='cemetery',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.cemetery'),
        ),
    ]
